@endpoint=http://localhost:8080

### Generator Code within Path 生成单表代码并返回代码路径
POST {{endpoint}}/api/cg/generate/code HTTP/1.1
content-type: application/json

{
    "module": "OneToManyRelation",
    "project": "OneToManyRelationItem",
    "tableName":"cg_chinese_area",
    "submodule": "relations",
    "sql":"cg_chinese_area.sql"
}

